# set arg vals
use.dat
test.fit
pred.vars.cont=NA
pred.vars.fact=NA
size=3
k=5
cyclic.vars=NA
linear.vars=NA
smooth.interactions=pred.vars.fact
factor.interactions=F
continuous.interactions=F
cov.cutoff=0.28
bs.arg="'cr'"
null.terms=""
max.models=500
parallel=F
n.cores=4
r2.type="r2.lm.est"
report.unique.r2=F
cor.matrix=NA