# set arg vals
use.dat
test.fit
pred.vars.cont=NA
pred.vars.fact=NA
cyclic.vars=NA
linear.vars=NA
max.predictors=3
k=5
factor.smooth.interactions=pred.vars.fact
factor.factor.interactions=F
smooth.smooth.interactions=F
cov.cutoff=0.28
bs.arg="'cr'"
null.terms=""
max.models=500
parallel=F
n.cores=4
r2.type="r2.lm.est"
report.unique.r2=F
cor.matrix=NA
factor.interactions="previous.arg"
smooth.interactions="previous.arg"
size="previous.arg"
check.non.linear.correlations=F